name: Build & Test

on: pull_request

env:
  MAVEN_VERSION: 3.9.9

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup maven
        uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: ${{ env.MAVEN_VERSION }}
      - name: Compile
        run: mvn --no-transfer-progress clean package
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup maven
        uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: ${{ env.MAVEN_VERSION }}
      - name: Run tests
        run: mvn --no-transfer-progress clean test -Ptest
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: files
          path: ./**/*.log
